### ISSUE TITLE
compatibility jeedom v4

### ISSUE THREAD

**Issue by fourniergwenn** [tlierdotfr/jeedom-plugin-rpict#2]
## Description
class object error in plugin parameters

Not working at all

## Etapes à reproduire (pour les bugs)
1.
2.
3.
4.

## Environnement
* **Version Jeedom**:
* **Platform**:
* **Version du Plugin (ex: 2.6.0)**:
* **Type de carte RPICT**:

## Logs
Merci de joindre les logs.

**Comment by tlierdotfr** [comment]
Try the Beta version ;-)
